### ISSUE TITLE
Bilder für Grundlagen

### ISSUE THREAD

**Issue by KonradHoeffner** [cubexy/BeLL#1]
- [ ] LOD Cloud für Verbreitung des Semantic Web: https://lod-cloud.net/
- [ ] https://en.wikipedia.org/wiki/Semantic_Web_Stack#/media/File:Semantic_web_stack.svg

Im PDF-Format abspeichern.

**Comment by KonradHoeffner** [comment]
# Semantic Web Stack
[semantic-web-stack.pdf](https://github.com/cubexy/BeLL/files/3916124/semantic-web-stack.pdf)
[semantic-web-stack-de.pdf](https://github.com/cubexy/BeLL/files/3916125/semantic-web-stack-de.pdf)
[semantic-web-stack-snik.pdf](https://github.com/cubexy/BeLL/files/3916126/semantic-web-stack-snik.pdf)
[semantic-web-stack-snik-de.pdf](https://github.com/cubexy/BeLL/files/3916127/semantic-web-stack-snik-de.pdf)
[semantic-web-stack-svgs.zip](https://github.com/cubexy/BeLL/files/3916129/semantic-web-stack-svgs.zip)

Bearbeitung am besten der SVGs mit Inkscape. Exportieren als PDF für LaTeX.

**Comment by cubexy** [comment]
[semantic_web_überarbeitet.zip](https://github.com/cubexy/BeLL/files/3916321/semantic_web_uberarbeitet.zip)

**Comment by KonradHoeffner** [comment]
[bb-cio.zip](https://github.com/cubexy/BeLL/files/3917072/bb-cio.zip)

**Comment by cubexy** [comment]
[semantic_web_ueberarbeitet2.zip](https://github.com/cubexy/BeLL/files/3917089/semantic_web_ueberarbeitet2.zip)

**Comment by cubexy** [comment]
[method-draw-image(1).pdf](https://github.com/cubexy/BeLL/files/3917101/method-draw-image.1.pdf)
